# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'IkeMtz Docker Hub'
        repository: 'ikemtz/sql_dacpac'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'beta'
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'synk'
        testType: 'container'
        dockerImageName: 'ikemtz/sql_dacpac:beta'
        dockerfilePath: 'Dockerfile'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: 'ikemtz/SQL_Dacpac'
    - task: Docker@2
      displayName: Test image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/test.Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'IkeMtz Docker Hub'
        repository: 'ikemtz/sql_dacpac'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest